### ISSUE TITLE
Svelte 5

### ISSUE THREAD

**Issue by nicholasglazer** [VerburgtJimmy/svelte-input-otp#4]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Any plans to migrate to svelte 5?

### What type of pull request would this be?

None

**Comment by VerburgtJimmy** [comment]
Thanks for this issue! I am currently on vacation so excuse my late reaction but I already started the migration before I went on vacation and I plan to finish and test it next week. I might create a next branch for this feature as it is a pretty big overhaul and needs some testing in the real world. I will leave this issue open for more info or request as part of the next big version

**Comment by VerburgtJimmy** [comment]
Closing this issue as i have created a new discussion for the svelte 5 version. If there are individual issue's or features for that version you can create a new issue here with the correct tags. Thanks
